name: 'Tests'

on: [ push ]

jobs:
  linux-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install Dependencies
        run: |
          # install C dependencies
          sudo apt-get install -y libxkbcommon-dev libwayland-dev

          # install odin
          export ODIN_VERSION=odin-ubuntu-amd64-dev-2025-01
          curl -LO https://github.com/odin-lang/Odin/releases/download/dev-2025-01/$ODIN_VERSION.zip
          unzip $ODIN_VERSION.zip
          tar -xzf dist.tar.gz
          export PATH=$PATH:$(pwd)/odin-linux-amd64-nightly+2025-01-08

          # install zigup
          export PATH=$PATH:$(pwd)
          curl -L https://github.com/marler8997/zigup/releases/download/v2025_01_02/zigup-x86_64-linux.tar.gz | tar xz
          ./zigup fetch $(cat zig_version.txt)

          # build all asset programs
          pushd assets > /dev/null
          ./build.sh CI
          popd > /dev/null

      - name: Run Tests (debug)
        run: |
          ./zigup run $(cat zig_version.txt) build --summary all -freference-trace -Drace -Dci -Dllvm
          ./zig-out/bin/inspect-tests

      - name: Run Tests (release safe)
        run: |
          ./zigup run $(cat zig_version.txt) build --summary all -freference-trace -Doptimize=ReleaseSafe -Dci -Dllvm
          ./zig-out/bin/inspect-tests
